### ISSUE TITLE
Possible fault in plugin when shown in sidebar with Akina Personal Blog Wordpress Theme

### ISSUE THREAD

**Issue by dbea3059** [gasatrya/recent-posts-widget-extended#26]
Hi there. the plugin in the last few days is not displaying correctly on our website. Just wondered if there was a problem with the plugin? We are using the latest version of the plugin and wordpress.

Here is a screenshot of the issue:[ ](https://imgur.com/59kMGlY)

We tried to submit a support question on your wordpress.org page but it didnt appear. If our question was posted incorrectly we apologise. There is little explanation for new users to understand how to use this site or understand how to communicate correctly. We would be able to communicate more effectively via email but if necessary will use this site to communicate.

If it is no longer possible to get support for this plugin could you please make this clear.

![example of faulty sidebar](https://user-images.githubusercontent.com/51986722/193661861-cb0aa19b-445a-49a1-8a9c-c32bf130655c.jpg)

**Comment by gasatrya** [comment]
Hi There,
Can you share your website URL? Also, are you using the latest version?

**Comment by gasatrya** [comment]
Please open new issue if you still see the problem
