### ISSUE TITLE
Shortcode for random not working

### ISSUE THREAD

**Issue by Zidster88** [gasatrya/recent-posts-widget-extended#27]
I'm trying to show one random post on my side bar with the usage of shortcode. 

[rpwe limit="1" orderby="random" thumb="true"]

Does give me a post, but it's not randomly changing. Any way to do this with shortcode?

**Comment by gasatrya** [comment]
Hi there,
Are you using any cache plugin?

**Comment by Zidster88** [comment]
Hi, thanks for your reply.
No, I am not using caching plugins. I have only a plugin for hiding meta-data. I have tried deactivating it, but it still doesn't work.

**Comment by gasatrya** [comment]
Oh I am sorry I just realized you put `random`, it should be just `rand`. Final code `[rpwe limit="1" orderby="rand" thumb="true"]`

**Comment by Zidster88** [comment]
Thanks, this works perfectly now :D I was wondering wether it was just a different input.

**Comment by gasatrya** [comment]
Yes, the `rand` value is from WordPress itself, sometimes people get confuse with the term :)
