### ISSUE TITLE
Trying to access array offset on value of type bool error

### ISSUE THREAD

**Issue by aadilovic-tfb** [gasatrya/recent-posts-widget-extended#7]
There is an error within lines 100 - 102 in _includes/resizer.php_. This is the referenced code:
        

            $dims = image_resize_dimensions($orig_w, $orig_h, $width, $height, $crop);
            $dst_w = $dims[4];
            $dst_h = $dims[5];

 The image_resize_dimensions() function returns an array with the dimensions if successful, however, if not successful it will return false. In the case that it is false, an error is generated due to attempting to set $dst_w and $dst_h to an array offset of false. A quick fix could be to simply check if $dims is an array, then setting the values of $dst_w/$dst_h, and if not, set $dst_w/$dst_h to null.

**Comment by gasatrya** [comment]
Fixed in version 2.0. Thanks!
